package main

import (
	"fmt"

	"github.com/alecthomas/kong"
	"github.com/miekg/king"
)

// CompletionCmd prints a shell completion script to stdout, generated from the
// live, fully-built kong grammar — so a new flag or subcommand is picked up
// automatically, with nothing to keep in sync by hand.
type CompletionCmd struct {
	Shell string `arg:"" enum:"bash,zsh,fish" help:"Shell to generate a completion script for."`
}

func (cmd *CompletionCmd) Run(kctx *kong.Context) error {
	c, err := completer(cmd.Shell)
	if err != nil {
		return err
	}
	// king.Completer.Completion mutates the node it's given (appends
	// completion-only flags, and may rename it via altname) — harmless here,
	// since this Run() is the last thing this process does with the parsed
	// model. Passing "" for altname reuses kong.Name("tranquila") from
	// buildParser rather than repeating the binary name in a second place.
	c.Completion(kctx.Model.Node, "")
	// Deliberately NOT king.Completer.Write: every implementation writes a
	// file into the current working directory (tranquila.bash/_tranquila/
	// tranquila.fish) as an unconditional side effect, in addition to any
	// writer passed in — surprising for a subcommand whose job is to print a
	// script to stdout for the caller to source or redirect themselves (the
	// usual `source <(tranquila completion bash)` shape). Out() returns the
	// generated bytes with no such side effect.
	_, err = kctx.Stdout.Write(c.Out())
	return err
}

// completer returns the king.Completer for shell. Reachable only with an
// enum value kong's own flag parsing has already validated, but returning an
// error here (rather than panicking) keeps the function itself correctly
// testable for an input kong would never actually let through.
func completer(shell string) (king.Completer, error) {
	switch shell {
	case "bash":
		return &king.Bash{}, nil
	case "zsh":
		return &king.Zsh{}, nil
	case "fish":
		return &king.Fish{}, nil
	default:
		return nil, fmt.Errorf("unsupported shell %q", shell)
	}
}
