{{- if eq (include "tranquila.createRedisSecret" .) "true" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tranquila.redisSecretName" . }}
  labels:
    {{- include "tranquila.labels" . | nindent 4 }}
type: Opaque
data:
  REDIS_ADDR: {{ include "tranquila.redisAddr" . | toString | b64enc }}
  REDIS_PASSWORD: {{ .Values.redis.password | b64enc }}
  REDIS_DB: {{ .Values.redis.db | toString | b64enc }}
{{- end }}
