{{- if not (include "tranquila.existingSecret" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tranquila.configSecretName" . }}
  labels:
    {{- include "tranquila.labels" . | nindent 4 }}
type: Opaque
data:
  SOURCE_ACCESS_KEY: {{ required "access key for source bucket needs to be specified if no existing secret is configured" .Values.config.source.accesskey | b64enc }}
  SOURCE_SECRET_KEY: {{ required "secret key for source bucket needs to be specified if no existing secret is configured" .Values.config.source.secretkey | b64enc }}
  DEST_ACCESS_KEY: {{ required "access key for destination bucket needs to be specified if no existing secret is configured" .Values.config.destination.accesskey | b64enc }}
  DEST_SECRET_KEY: {{ required "secret key for destination bucket needs to be specified if no existing secret is configured" .Values.config.destination.secretkey | b64enc }}
{{- end }}
