apiVersion: v1
kind: Service
metadata:
  name: {{ include "tranquila.fullname" . }}
  labels:
    {{- include "tranquila.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.managementApi.name }}
      protocol: TCP
      name:  {{ .Values.managementApi.name }}
    {{- if and .Values.metrics.enabled .Values.metrics.service.enabled (eq .Values.metrics.type "prometheus")}}
    - port: {{ .Values.metrics.prometheus.port }}
      targetPort: {{ .Values.metrics.prometheus.name }}
      protocol: TCP
      name: {{ .Values.metrics.prometheus.name }}
    {{- end }}
  selector:
    {{- include "tranquila.selectorLabels" . | nindent 4 }}
